{% set name = "seamless-3dep" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seamless_3dep-{{ version }}.tar.gz
  sha256: 672016a3d04ab6de2fa6f282cc3c781c710ed37d69cbc16dd7db61fa935c70c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - tiny-retriever >=0.1.1
    - libgdal-core
    - rasterio
    - numpy >=2

test:
  imports:
    - seamless_3dep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Streamlined Access to USGS 3DEP Topographic Data
  license: MIT
  license_file: LICENSE
  home: https://seamless-3dep.readthedocs.io
  doc_url: https://seamless-3dep.readthedocs.io
  dev_url: https://github.com/hyriver/seamless-3dep

extra:
  recipe-maintainers:
    - cheginit
